name: grisette-generics
version: 0.1.0.0
synopsis: Extension to Grisette for unifying the interface for symbolic and concrete types.
category: Formal Methods, Theorem Provers, Symbolic Computation, SMT
author: "Sirui Lu, Rastislav Bodík"
maintainer: Sirui Lu (siruilu@cs.washington.edu)
license: BSD3
license-file: LICENSE
github: lsrcz/grisette-generics
copyright: "2024 Sirui Lu"
extra-source-files:
  - CHANGELOG.md
  - README.md
tested-with:
  - GHC == 9.2.8
  - GHC == 9.4.8
  - GHC == 9.6.3
  - GHC == 9.8.1

dependencies:
  - base >= 4.14 && < 5
  - grisette >= 0.5.0.0 && < 0.6
  - deepseq >= 1.4.4 && < 1.6
  - template-haskell >= 2.16.0 && < 2.22
  - mtl >= 2.2.2 && < 2.4
  - hashable >= 1.2.3 && < 1.5

ghc-options:
  - -Wextra
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wmissing-import-lists
  - -Wpartial-fields
  - -Wunused-type-patterns

library:
  source-dirs: src

tests:
  spec:
    main: Main.hs
    source-dirs: test
    dependencies:
      - grisette
      - grisette-generics
